variables:
  DOCFX_SOURCE_BRANCH_NAME: $CI_BUILD_REF_NAME  

build_lib:
  stage: build
  image: mono:5.8
  script:
    - export BUILD_VERSION=$(echo $CI_COMMIT_REF_NAME | sed  's/\([0-9]\+\.[0-9]\+\.[0-9]\+\)\-release$/\1/g')
    - echo $BUILD_VERSION
    - sed -i -e "s/0.5.1.0/$BUILD_VERSION.0/g" Assets/Plugins/Rayark/Mast/Properties/AssemblyInfo.cs
    - ./build.sh
  artifacts:
    paths:
      - build
  tags:
    - docker-runner
  only:
    - /^.*-release$/

build_doc:
  stage: build
  image: alvinsay/docfx:2.32.1
  script:
    - docfx doc/docfx.json
    - mv doc/_site public
  artifacts:
    paths:
      - public                       # Upload the directory
  tags:
    - docker-runner
  only:
    - /^.*-release$/


pages:
  stage: deploy
  image: alvinsay/docfx:2.32.1
  script:
    - docfx doc/docfx.json
    - mv doc/_site public
  artifacts:
    paths:
      - public                       # Upload the directory
  tags:
    - docker-runner
  only:
    - develop
